# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62ba45a2b2ae30294be55726a1aed1be32da1d552b59ce0d957403952122b51b9aa518524124c2b51c172cbc54e9d926a5cc17c1aeb7570ae1ac624a113af489

test:
  secret_key_base: 7577f853c66064369e452ce3c9625fd5b0f25d2ae715825936f05b995aaa6eb08b20893ea325a58434a1e49865eb692da64287cd97c7afa957dcf1419f92c730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
